USE codeup_test_db

CREATE TABLE albums (
id INT UNSIGNED NOT NULL AUTO_INCREMENT,
artist VARCHAR(50) NOT NULL,
name VARCHAR(100) NOT NULL,
release_date DATE DEFAULT NULL,
sales INT UNSIGNED DEFAULT NULL,
genre VARCHAR(100) NOT NULL,
PRIMARY KEY (id)
    );